require "../spec_helper"

describe "PDF Generation Integration" do
  describe "simple document" do
    it "generates a valid PDF with text" do
      doc = PDF::Document.new
      doc.title = "Test Document"
      doc.author = "Crystal PDF"

      doc.page do |page|
        page.font "Helvetica", size: 24
        page.text "Hello, World!", at: {72, 720}

        page.font "Helvetica", size: 12
        page.text "This is a test PDF generated by pdf.cr", at: {72, 680}
      end

      bytes = doc.to_slice

      # Verify PDF structure
      String.new(bytes).should start_with("%PDF-1.7")
      String.new(bytes).should contain("%%EOF")
      String.new(bytes).should contain("/Type /Catalog")
      String.new(bytes).should contain("/Type /Pages")
      String.new(bytes).should contain("/Type /Page")
      String.new(bytes).should contain("/Helvetica")
    end

    it "generates multi-page document" do
      doc = PDF::Document.new

      3.times do |i|
        doc.page do |page|
          page.font "Times-Roman", size: 18
          page.text "Page #{i + 1}", at: {72, 720}
        end
      end

      bytes = doc.to_slice
      content = String.new(bytes)

      # Should have 3 pages
      content.should contain("/Count 3")

      # Should have Kids array with 3 references
      content.should contain("/Kids [")
    end

    it "generates document with graphics" do
      doc = PDF::Document.new

      doc.page do |page|
        # Red rectangle
        page.fill_color(1.0, 0.0, 0.0)
        page.rectangle(72, 600, 100, 50)
        page.fill

        # Blue line
        page.stroke_color(0.0, 0.0, 1.0)
        page.line_width(2)
        page.move_to(72, 500)
        page.line_to(200, 500)
        page.stroke
      end

      bytes = doc.to_slice

      # Check header and trailer
      bytes.size.should be > 100
      String.new(bytes[0, 8]).should start_with("%PDF-1.7")

      # Verify structure is present (scan as bytes to avoid UTF-8 issues)
      bytes_str = String.new(bytes)
      bytes_str.should contain("/Type /Page")
      bytes_str.should contain("/Contents")
      bytes_str.should contain("/FlateDecode")
    end

    it "uses different fonts" do
      doc = PDF::Document.new

      doc.page do |page|
        page.font "Helvetica", size: 12
        page.text "Helvetica", at: {72, 720}

        page.font "Helvetica-Bold", size: 12
        page.text "Helvetica Bold", at: {72, 700}

        page.font "Times-Roman", size: 12
        page.text "Times Roman", at: {72, 680}

        page.font "Courier", size: 12
        page.text "Courier", at: {72, 660}
      end

      bytes = doc.to_slice
      content = String.new(bytes)

      content.should contain("/Helvetica")
      content.should contain("/Helvetica-Bold")
      content.should contain("/Times-Roman")
      content.should contain("/Courier")
    end
  end

  describe "page sizes" do
    it "supports A4 size" do
      doc = PDF::Document.new
      doc.page(size: :a4) { |p| p.font("Helvetica", size: 12) }

      bytes = doc.to_slice
      content = String.new(bytes)

      # A4 is 595 x 842 points
      content.should contain("/MediaBox [0 0 595 842]")
    end

    it "supports landscape orientation" do
      doc = PDF::Document.new
      doc.page(size: :letter, orientation: :landscape) { |p| p.font("Helvetica", size: 12) }

      bytes = doc.to_slice
      content = String.new(bytes)

      # Letter landscape is 792 x 612
      content.should contain("/MediaBox [0 0 792 612]")
    end
  end

  describe "file output" do
    it "saves to file" do
      doc = PDF::Document.new
      doc.page do |page|
        page.font "Helvetica", size: 12
        page.text "Test", at: {72, 720}
      end

      temp_path = File.tempname("test", ".pdf")
      begin
        doc.save(temp_path)
        File.exists?(temp_path).should be_true
        File.size(temp_path).should be > 0

        content = File.read(temp_path)
        content.should start_with("%PDF-1.7")
      ensure
        File.delete(temp_path) if File.exists?(temp_path)
      end
    end
  end

  describe "TrueType fonts" do
    it "generates PDF with TrueType font" do
      doc = PDF::Document.new
      custom_font = doc.load_font("spec/fixtures/fonts/DejaVuSans.ttf")

      doc.page do |page|
        page.font custom_font, size: 24
        page.text "Hello with TrueType!", at: {72, 720}

        page.font custom_font, size: 12
        page.text "Custom font embedding works!", at: {72, 680}
      end

      bytes = doc.to_slice

      # Verify PDF structure
      content = String.new(bytes)
      content.should start_with("%PDF-1.7")
      content.should contain("%%EOF")
      content.should contain("/Type /Catalog")
      content.should contain("/Type /Page")

      # Should have TrueType font structures
      content.should contain("/Type0")
      content.should contain("/CIDFontType2")
      content.should contain("/FontDescriptor")
      content.should contain("/FontFile2")
      content.should contain("/ToUnicode")
    end

    it "supports Unicode text with TrueType" do
      doc = PDF::Document.new
      custom_font = doc.load_font("spec/fixtures/fonts/DejaVuSans.ttf")

      doc.page do |page|
        page.font custom_font, size: 18
        # Various Unicode characters
        page.text "Hello World! (ASCII)", at: {72, 720}
        page.text "Привет мир! (Cyrillic)", at: {72, 690}
        page.text "日本語 (Japanese)", at: {72, 660}
      end

      bytes = doc.to_slice

      # Should generate valid PDF
      content = String.new(bytes)
      content.should start_with("%PDF-1.7")
      content.should contain("/Identity-H")
    end

    it "mixes Type1 and TrueType fonts" do
      doc = PDF::Document.new
      custom_font = doc.load_font("spec/fixtures/fonts/DejaVuSans.ttf")

      doc.page do |page|
        page.font "Helvetica", size: 18
        page.text "Standard Helvetica", at: {72, 720}

        page.font custom_font, size: 18
        page.text "Custom TrueType", at: {72, 690}

        page.font "Times-Roman", size: 18
        page.text "Standard Times", at: {72, 660}
      end

      bytes = doc.to_slice
      content = String.new(bytes)

      # Should have both font types
      content.should contain("/Helvetica")
      content.should contain("/Times-Roman")
      content.should contain("/CIDFontType2")
    end

    it "reuses same font across pages" do
      doc = PDF::Document.new
      custom_font = doc.load_font("spec/fixtures/fonts/DejaVuSans.ttf")

      3.times do |i|
        doc.page do |page|
          page.font custom_font, size: 18
          page.text "Page #{i + 1}", at: {72, 720}
        end
      end

      bytes = doc.to_slice

      # Should have 3 pages
      content = String.new(bytes)
      content.should contain("/Count 3")
    end

    it "saves TrueType PDF to file" do
      doc = PDF::Document.new
      custom_font = doc.load_font("spec/fixtures/fonts/DejaVuSans.ttf")

      doc.page do |page|
        page.font custom_font, size: 24
        page.text "TrueType Font Test", at: {72, 720}
      end

      temp_path = File.tempname("truetype_test", ".pdf")
      begin
        doc.save(temp_path)
        File.exists?(temp_path).should be_true
        File.size(temp_path).should be > 0

        content = File.read(temp_path)
        content.should start_with("%PDF-1.7")
        content.should contain("/CIDFontType2")
      ensure
        File.delete(temp_path) if File.exists?(temp_path)
      end
    end

    it "handles subset correctly" do
      doc = PDF::Document.new
      custom_font = doc.load_font("spec/fixtures/fonts/DejaVuSans.ttf")

      doc.page do |page|
        page.font custom_font, size: 12
        page.text "ABC", at: {72, 720}
      end

      bytes1 = doc.to_slice

      # Create another document with more text
      doc2 = PDF::Document.new
      custom_font2 = doc2.load_font("spec/fixtures/fonts/DejaVuSans.ttf")

      doc2.page do |page|
        page.font custom_font2, size: 12
        page.text "The quick brown fox jumps over the lazy dog.", at: {72, 720}
      end

      bytes2 = doc2.to_slice

      # The second PDF should be larger due to more glyphs
      # (This is a rough test - exact sizes depend on subsetting)
      bytes2.size.should be > bytes1.size
    end
  end

  describe "Images" do
    it "generates PDF with JPEG image" do
      doc = PDF::Document.new
      jpeg = PDF::Images::JPEG.load("spec/fixtures/images/test_rgb.jpg")

      doc.page do |page|
        page.font "Helvetica", size: 18
        page.text "JPEG Image Test", at: {72, 750}
        page.image jpeg, at: {72, 500}, width: 200
      end

      bytes = doc.to_slice
      content = String.new(bytes)

      # Verify PDF structure
      content.should start_with("%PDF-1.7")
      content.should contain("%%EOF")
      content.should contain("/Type /XObject")
      content.should contain("/Subtype /Image")
      content.should contain("/DCTDecode")
      content.should contain("/XObject")
    end

    it "generates PDF with PNG image" do
      doc = PDF::Document.new
      png = PDF::Images::PNG.load("spec/fixtures/images/test_rgb.png")

      doc.page do |page|
        page.font "Helvetica", size: 18
        page.text "PNG Image Test", at: {72, 750}
        page.image png, at: {72, 500}, width: 200
      end

      bytes = doc.to_slice
      content = String.new(bytes)

      # Verify PDF structure
      content.should start_with("%PDF-1.7")
      content.should contain("/Type /XObject")
      content.should contain("/Subtype /Image")
      content.should contain("/FlateDecode")
    end

    it "generates PDF with PNG with alpha" do
      doc = PDF::Document.new
      png = PDF::Images::PNG.load("spec/fixtures/images/test_rgba.png")

      doc.page do |page|
        # Draw a colored background to show transparency
        page.fill_color(0.2, 0.4, 0.8)
        page.rectangle(50, 480, 220, 220)
        page.fill

        page.font "Helvetica", size: 18
        page.text "PNG with Alpha Test", at: {72, 750}
        page.image png, at: {72, 500}, width: 200
      end

      bytes = doc.to_slice
      content = String.new(bytes)

      # Verify PDF structure with soft mask
      content.should start_with("%PDF-1.7")
      content.should contain("/Type /XObject")
      content.should contain("/SMask")
      content.should contain("/DeviceGray")
    end

    it "auto-detects image format" do
      doc = PDF::Document.new
      jpeg = PDF::Images::Image.load("spec/fixtures/images/test_rgb.jpg")
      png = PDF::Images::Image.load("spec/fixtures/images/test_rgb.png")

      doc.page do |page|
        page.font "Helvetica", size: 18
        page.text "Auto-detect Image Format", at: {72, 750}
        page.image jpeg, at: {72, 500}, width: 150
        page.image png, at: {272, 500}, width: 150
      end

      bytes = doc.to_slice
      content = String.new(bytes)

      # Should have both DCT (JPEG) and FlateDecode (PNG) images
      content.should contain("/DCTDecode")
      content.should contain("/FlateDecode")
    end

    it "scales images correctly" do
      doc = PDF::Document.new
      image = PDF::Images::JPEG.load("spec/fixtures/images/test_rgb.jpg")

      doc.page do |page|
        page.font "Helvetica", size: 12
        page.text "Original size (100x100):", at: {72, 700}
        page.image image, at: {72, 580}

        page.text "Width: 50 (scaled):", at: {200, 700}
        page.image image, at: {200, 580}, width: 50

        page.text "Height: 80 (scaled):", at: {280, 700}
        page.image image, at: {280, 580}, height: 80

        page.text "Scale: 0.5:", at: {400, 700}
        page.image image, at: {400, 580}, scale: 0.5

        page.text "Width & Height (distorted):", at: {72, 450}
        page.image image, at: {72, 330}, width: 100, height: 50
      end

      bytes = doc.to_slice

      # Just verify it generates without error
      String.new(bytes).should start_with("%PDF-1.7")
    end

    it "places multiple images on same page" do
      doc = PDF::Document.new
      jpeg = PDF::Images::JPEG.load("spec/fixtures/images/test_rgb.jpg")
      png = PDF::Images::PNG.load("spec/fixtures/images/test_rgba.png")

      doc.page do |page|
        page.font "Helvetica", size: 18
        page.text "Multiple Images", at: {72, 750}

        # Tile images
        3.times do |row|
          3.times do |col|
            x = 72 + col * 180
            y = 500 - row * 180
            if (row + col) % 2 == 0
              page.image jpeg, at: {x, y}, width: 150
            else
              page.image png, at: {x, y}, width: 150
            end
          end
        end
      end

      bytes = doc.to_slice
      String.new(bytes).should start_with("%PDF-1.7")
    end

    it "saves image PDF to file" do
      doc = PDF::Document.new
      image = PDF::Images::JPEG.load("spec/fixtures/images/test_rgb.jpg")

      doc.page do |page|
        page.font "Helvetica", size: 18
        page.text "Image to File Test", at: {72, 750}
        page.image image, at: {72, 500}, width: 200
      end

      temp_path = File.tempname("image_test", ".pdf")
      begin
        doc.save(temp_path)
        File.exists?(temp_path).should be_true
        File.size(temp_path).should be > 0

        content = File.read(temp_path)
        content.should start_with("%PDF-1.7")
        content.should contain("/DCTDecode")
      ensure
        File.delete(temp_path) if File.exists?(temp_path)
      end
    end

    it "reuses same image across multiple placements" do
      doc = PDF::Document.new
      image = PDF::Images::JPEG.load("spec/fixtures/images/test_rgb.jpg")

      doc.page do |page|
        page.font "Helvetica", size: 12
        page.text "Same image used multiple times:", at: {72, 750}

        # Place same image at different positions and sizes
        page.image image, at: {72, 600}, width: 100
        page.image image, at: {200, 600}, width: 50
        page.image image, at: {280, 600}, width: 150
      end

      bytes = doc.to_slice
      content = String.new(bytes)

      # Should only have one XObject resource, used multiple times
      content.should contain("/Im1")
      # The Do operator should appear 3 times
      String.new(bytes).should start_with("%PDF-1.7")
    end
  end
end
